### ISSUE TITLE
Freemode

### ISSUE THREAD

**Issue by RobbanGit** [DIT112-V21/group-11#34]
User Story:

As a first-time user, I would like to be given the opportunity play around in freemode, so that I may prepare for the other mode(s).

Acceptance Criteria:

Upon starting up the program, the user shall be given the opportunity to either choose freemode or time trial.
In the freemode, the user shall be able to drive around without any other restrictions/features interrupting the gameplay.

**Comment by Jidarv** [comment]
We decided not to implement this feature.
